// Generated by gencpp from file f1tenth_simulator/AddTwoInts.msg
// DO NOT EDIT!


#ifndef F1TENTH_SIMULATOR_MESSAGE_ADDTWOINTS_H
#define F1TENTH_SIMULATOR_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <f1tenth_simulator/AddTwoIntsRequest.h>
#include <f1tenth_simulator/AddTwoIntsResponse.h>


namespace f1tenth_simulator
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace f1tenth_simulator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::f1tenth_simulator::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::f1tenth_simulator::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::f1tenth_simulator::AddTwoInts > {
  static const char* value()
  {
    return "f1tenth_simulator/AddTwoInts";
  }

  static const char* value(const ::f1tenth_simulator::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::f1tenth_simulator::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::f1tenth_simulator::AddTwoInts >
template<>
struct MD5Sum< ::f1tenth_simulator::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::f1tenth_simulator::AddTwoInts >::value();
  }
  static const char* value(const ::f1tenth_simulator::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::f1tenth_simulator::AddTwoIntsRequest> should match
// service_traits::DataType< ::f1tenth_simulator::AddTwoInts >
template<>
struct DataType< ::f1tenth_simulator::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::f1tenth_simulator::AddTwoInts >::value();
  }
  static const char* value(const ::f1tenth_simulator::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::f1tenth_simulator::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::f1tenth_simulator::AddTwoInts >
template<>
struct MD5Sum< ::f1tenth_simulator::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::f1tenth_simulator::AddTwoInts >::value();
  }
  static const char* value(const ::f1tenth_simulator::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::f1tenth_simulator::AddTwoIntsResponse> should match
// service_traits::DataType< ::f1tenth_simulator::AddTwoInts >
template<>
struct DataType< ::f1tenth_simulator::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::f1tenth_simulator::AddTwoInts >::value();
  }
  static const char* value(const ::f1tenth_simulator::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // F1TENTH_SIMULATOR_MESSAGE_ADDTWOINTS_H
